---
title: 'Reproducible Research: Peer Assessment 1'
output:
  html_document:
    highlight: tango
    keep_md: yes
    theme: readable
---
```{r setoptions, echo=FALSE}
library(knitr)
opts_chunk$set(echo = TRUE)
```

## Loading and preprocessing the data
```{r part1-code1}
#Load the data.
raw_data <- read.csv("activity.csv")
str(raw_data)
```


## What is mean total number of steps taken per day?
```{r part2-code1}
suppressMessages(library(dplyr))
#Calculate the total number of steps taken per day.
data <- group_by(raw_data, date) %>% 
    summarise(total_steps = sum(steps, na.rm = TRUE))
str(data)
```
```{r part2-plot1}
#Make a histogram of the total number of steps taken each day.
hist(data$total_steps, 
     main = "Total Number of Steps Taken Each Day", 
     xlab = "Total number of steps taken each day")
```
```{r part2-code2}
#Calculate the mean and median of the total number of steps taken per day.
mean(data$total_steps)
median(data$total_steps)
```


## What is the average daily activity pattern?
```{r part3-code1}
suppressMessages(library(dplyr))
data <- group_by(raw_data, interval) %>% 
    summarise(avg_steps = mean(steps, na.rm = TRUE))
str(data)
```
```{r part3-plot1}
#Make a time series plot.
plot(data$interval, data$avg_steps, type = "l",
     main = "Average Number of Steps Taken Across All Days",
     xlab = "5-minute interval",
     ylab = "Average number of steps taken")
```
```{r part3-code2}
#Show 5-minute interval, on average across all the days in the dataset, 
#contains the maximum number of steps.
data[which(data$avg_steps == max(data$avg_steps)), 1:2]
```


## Imputing missing values
```{r part4-code1}
detach("package:dplyr", unload = TRUE)
suppressMessages(library(plyr))
suppressMessages(library(dplyr))
#Calculate the total number of rows with NAs.
sum(is.na(raw_data$steps))
#Fill in all of the missing values in the dataset with the mean that 5-minute 
#interval. And then create a new dataset that is equal to the original dataset, 
#but with the missing data filled in.
raw_data[raw_data$interval == 5 & is.na(raw_data$steps), ]
m <- mean(raw_data[raw_data$interval == 5, 1], na.rm = T)
impute.mean <- function(x) replace(x, is.na(x), mean(x, na.rm = TRUE))
data <- ddply(raw_data, ~ interval, transform, steps = impute.mean(steps))   
data[data$interval == 5 & data$steps == m, ]
data_grouped <- group_by(raw_data, date) %>% 
    summarise(total_steps = sum(steps, na.rm = TRUE))
```
```{r part4-plot1}
#Make a histogram of the total number of steps taken each day.
hist(data_grouped$total_steps, 
     main = "Total Number of Steps Taken Each Day (without NAs)", 
     xlab = "Total number of steps taken each day")
```
```{r part4-code2}
#Calculate the mean and median total number of steps taken per day.
mean(data_grouped$total_steps)
median(data_grouped$total_steps)
#Do these values differ from the estimates from the first part of 
#the assignment? 
#[Ans] These values are same as the first part of the assignment.
#What is the impact of imputing missing data on the estimates of 
#the total daily number of steps?
#[Ans] Imputing missing data does not show significant impact.
```


## Are there differences in activity patterns between weekdays and weekends?
```{r part5-code1}
#Use the dataset with the filled-in missing values for this part.
str(data)
#Create a new factor variable in the dataset with two levels: 'weekday', 
#'weekend' indicating whether a given date is a weekday or weekend day.
suppressMessages(library(lubridate))
suppressMessages(library(dplyr))
suppressMessages(library(chron))
suppressMessages(library(ggplot2))
data <- mutate(data, 
    day_type = factor(ifelse(is.weekend(ymd(date)), "weekend", "weekday")))
str(data)
```
``` {r part5-plot1}
#Make a panel plot containing a time series plot.
data.grouped <- group_by(data, interval, day_type) %>% 
    summarise(avg_steps = mean(steps, na.rm = TRUE))
qplot(interval, avg_steps, data = data.grouped, 
      geom = "line", facets = day_type ~ .) +
    xlab("5-minute interval") +
    ylab("Average number of steps taken") +
    ggtitle("Activity Patterns Between Weekdays and Weekend")
```


## Ref.:
- [How to substitute missing values by the group means](https://www.mail-archive.com/r-help@r-project.org/msg58289.html)
